# 鉴权配置

jwt:
  secret: nestservedyb881 # 加密串，生产环境必须更改
  expiresIn: 36000s # 过期时间

# 权限配置

permission:
  # 权限动作
  actions: [query, create, update, delete]
  # 权限模块
  apps:
    # 账号模块
    account: [adminRole, admin, user]
    # 信息模块
    infos: [category, article]
    # 系统模块
    system: [files]
