# 鉴权配置

jwt:
  secret: nestservedyb881 # 加密串，生产环境必须更改
  expiresIn: 36000s # 过期时间

# 权限动作

permissionAction: [query, create, update, delete]

# 权限配置

permissions:
  account: [adminRole, admin, user]
  infos: [category, information]
  system: [files]
